new_basket=["axay","darshit","avi","vishal","jaydeep","meet"]
new_baskets=["gautam"]
basket=['a','f','r','y','x','z']
print(basket)
basket.sort()
print(basket)
basket.reverse()
print(basket)
print(sorted(new_basket))
new_basket.extend(new_baskets)
print(sorted(new_basket))
